.PHONY: up down build logs migrate revision shell seed test

up:
	docker compose up --build

down:
	docker compose down

build:
	docker compose build

logs:
	docker compose logs -f backend worker

# Run Alembic migrations inside the backend container.
migrate:
	docker compose run --rm backend alembic upgrade head

# Create a new autogenerated migration: make revision m="message"
revision:
	docker compose run --rm backend alembic revision --autogenerate -m "$(m)"

shell:
	docker compose exec backend bash

seed:
	docker compose run --rm backend python -m scripts.seed

test:
	docker compose run --rm backend pytest
